-- Your SQL goes here
CREATE TABLE meal_plans (
  id UUID PRIMARY KEY,
  "week" SMALLINT NOT NULL,
  "year" SMALLINT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);